import React from "react";
import Navbar from "@/src/components/Navbar";
import Head from "next/head";

const index = () => {
  return (
    <div>
      <Head>
        <title> Downloads | Weave</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      index
    </div>
  );
};

export default index;
