import { NextPage } from "next";
import Image from "next/image";
import { Inter } from "@next/font/google";
import Navbar from "@/src/components/home/Navbar";
import Footer from "@/src/components/home/Footer";
import Logo from "@/public/Logo - solid.png";
import DownloadButton from "@/src/components/home/DownloadButton";
import { useContext } from "react";
import Head from "next/head";
import Parallax from "@/src/components/home/Parallax";
import Parallax_2 from "@/src/components/home/Parallax_2";
import ThemeContext from "../components/ThemeContextProvider";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const { isDarkTheme } = useContext(ThemeContext);
  return (
    <>
      <div
        id="bottomGradient"
        className={`${isDarkTheme ? "bottomGradient" : "bottomGradientLight"}`}
      >
        <Head>
          <title>Weave</title>
          <meta name="description" content="Generated by create-t3-app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Navbar />
        <div className={inter.className}>
          <div
            className={`${
              isDarkTheme ? "topGradient" : "topGradientLight"
            } h-screen`}
          >
            <div className="z-50 pt-24">
              <Parallax_2 />
            </div>
            <div className="flex justify-center pt-28">
              <Image src={Logo} alt="logo" width={160} height={160} />
            </div>
            <h1 className="mt-24 text-center text-5xl font-semibold tracking-widest text-[#171717] dark:text-[#E2E2E2]">
              Group Hangouts.
              <br /> Encrypted
            </h1>
            <div className="-z-10 my-24 flex justify-center">
              <DownloadButton />
            </div>
            <div className="mt-8 text-center tracking-widest text-[#171717] dark:text-[#E2E2E2]">
              <h2 className="text-4xl">For work, gaming or just chatting.</h2>
              <h4 className="text-md">
                For each use case Weave provides seamless features to focus on
                what matters.
              </h4>
              <span className="text-2xl">Text or voice,</span>
              <br />
              <span className="text-lg">
                everything is end-to-end encrypted
              </span>
            </div>
          </div>
          <Parallax />
          <div
            id="spacer"
            className="z-0 mx-36 mt-36 h-screen rounded-[3rem] bg-[url('/work.jpg')] bg-cover"
          ></div>
        </div>
        <div className="mx-12 mb-4 mt-12 border-b border-[#171717] dark:border-[#E2E2E2]" />
        <Footer />
      </div>
    </>
  );
}
