import { NextPage } from "next";
import Image from "next/image";
import { Inter } from "@next/font/google";
import Navbar from "@/src/components/Navbar";
import Footer from "@/src/components/Footer";
import Logo from "@/public/Logo - solid.png";
import DownloadButton from "../components/DownloadButton";
import { useEffect, useRef, useState } from "react";
import Head from "next/head";
import { useTheme as useNextTheme } from "next-themes";
import { Switch, useTheme } from "@nextui-org/react";
import Parallax from "../components/Parallax";
import Parallax_2 from "../components/Parallax_2";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [isDarkTheme, setDarkTheme] = useState(false);
  const [fillColor, setFillColor] = useState("#171717");
  const { setTheme } = useNextTheme();
  const { isDark, type } = useTheme();
  function darkModeToggle() {
    setDarkTheme(!isDarkTheme);
    if (isDarkTheme) {
      document.getElementById("html")?.classList.remove("dark");
      document.getElementById("html")?.setAttribute("class", "bg-zinc-300");
      document
        .getElementById("body")
        ?.setAttribute("class", "bgColorGradientLight");
      document
        .getElementById("topGradient")
        ?.setAttribute("class", "topGradientLight");
      document
        .getElementById("bottomGradient")
        ?.setAttribute("class", "bottomGradientLight");
      setTheme("light");
      setFillColor("#171717");
    } else {
      document
        .getElementById("html")
        ?.setAttribute("class", "dark bg-[#262626]");
      document
        .getElementById("topGradient")
        ?.setAttribute("class", "topGradient");
      document
        .getElementById("bottomGradient")
        ?.setAttribute("class", "bottomGradient");
      setTheme("dark");
      document.getElementById("body")?.setAttribute("class", "bgColorGradient");
      setFillColor("#E2E2E2");
    }
  }
  useEffect(() => {
    setDarkTheme(window.matchMedia("(prefers-color-scheme: dark)").matches);
    if (window.matchMedia("(prefers-color-scheme: dark)").matches) {
      document.getElementById("html")?.classList.add("dark");
      setFillColor("#E2E2E2");
    } else {
      document.getElementById("html")?.classList.remove("dark");
      setFillColor("#171717");
    }
  }, []);

  return (
    <>
      <Head>
        <title>Weave</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar darkModeToggle={darkModeToggle} isDarkTheme={isDarkTheme} />
      <div className={inter.className}>
        <div id="topGradient" className="topGradient h-screen">
          <div className="z-50 pt-24">
            <Parallax_2 fillColor={fillColor} />
          </div>
          <div className="flex justify-center pt-28">
            <Image src={Logo} alt="logo" width={160} height={160} />
          </div>
          <h1 className="mt-24 text-center text-5xl font-semibold tracking-widest text-[#171717] dark:text-[#E2E2E2]">
            Group Hangouts.
            <br /> Encrypted
          </h1>
          <div className="-z-10 my-24 flex justify-center">
            <DownloadButton />
          </div>
          <div className="mt-8 text-center tracking-widest text-[#171717] dark:text-[#E2E2E2]">
            <h2 className="text-4xl">For work, gaming or just chatting.</h2>
            <h4 className="text-md">
              For each use case Weave provides seamless features to focus on
              what matters.
            </h4>
            <span className="text-2xl">Text or voice,</span>
            <br />
            <span className="text-lg">everything is end-to-end encrypted</span>
          </div>
        </div>
        <Parallax fillColor={fillColor} />
        <div
          id="spacer"
          className="z-0 mx-36 mt-36 h-screen rounded-[3rem] bg-[url('/work.jpg')] bg-cover"
        ></div>
      </div>
      <div className="mx-12 mb-4 mt-12 border-b border-[#171717] dark:border-[#E2E2E2]" />
      <Footer fillColor={fillColor} />
    </>
  );
}
