import React, {
  createContext,
  useContext,
  useEffect,
  useRef,
  useState,
} from "react";
import Navbar from "@/src/components/Navbar";
import Head from "next/head";
import ThemeContext from "@/src/components/ThemeContextProvider";
import SideNav from "@/src/components/app/SideNav";
import ServerModal from "@/src/components/app/ServerModal";
import useOnClickOutside from "@/src/components/ClickOutsideHook";
import BotServiceModal from "@/src/components/app/BotServiceModal";
import InnerNav from "@/src/components/app/InnerNav";
import DirectMessageModal from "@/src/components/app/DirectMessageModal";
import PublicServersPages from "@/src/components/app/PublicServersPages";
import DMPages from "@/src/components/app/DMPages";

const index = () => {
  const { isDarkTheme } = useContext(ThemeContext);
  const [serverModalShowing, setServerModalShowing] = useState(false);
  const [botModalShowing, setBotModalShowing] = useState(false);

  const [currentTab, setCurrentTab] = useState("DMS");
  const [selectedInnerTab, setSelectedInnerTab] = useState("");

  const switchRef = useRef<HTMLDivElement>(null);
  const serverModalRef = useRef<HTMLDivElement>(null);
  const serverButtonRef = useRef<HTMLButtonElement>(null);
  const botModalRef = useRef<HTMLDivElement>(null);
  const botButtonRef = useRef<HTMLButtonElement>(null);

  const [direcMessageModalShowing, setDirecMessageModalShowing] =
    useState(false);
  const directMessageButtonRef = useRef<HTMLButtonElement>(null);
  const directMessageModalRef = useRef<HTMLDivElement>(null);

  const scrollableRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    if (scrollableRef.current) {
      scrollableRef.current.scrollTop = scrollableRef.current.scrollHeight;
    }
  }, []);

  useOnClickOutside([directMessageModalRef, directMessageButtonRef], () => {
    setDirecMessageModalShowing(false);
  });

  function dmModalToggle() {
    setDirecMessageModalShowing(!direcMessageModalShowing);
  }

  function currentTabSetter(id: string) {
    setCurrentTab(id);
  }

  useEffect(() => {
    document.getElementById("html")?.classList.add("scollDisabled");
    document
      .getElementById("body")
      ?.setAttribute("class", "bg-zinc-300 dark:bg-zinc-700");
  }, []);

  useEffect(() => {
    if (serverModalShowing || botModalShowing || direcMessageModalShowing) {
      document.getElementById("app-body")?.classList.add("modal-open");
    } else {
      document.getElementById("app-body")?.classList.remove("modal-open");
    }
  }, [serverModalShowing, botModalShowing, direcMessageModalShowing]);

  useOnClickOutside([serverModalRef, serverButtonRef, switchRef], () =>
    setServerModalShowing(false)
  );
  useOnClickOutside([botModalRef, botButtonRef, switchRef], () =>
    setBotModalShowing(false)
  );

  function serverModalToggle() {
    setServerModalShowing(!serverModalShowing);
  }

  function botModalToggle() {
    setBotModalShowing(!botModalShowing);
  }

  return (
    <div className="bg-zinc-300 dark:bg-zinc-700">
      <Head>
        <title> Web App | Weave</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar switchRef={switchRef} />
      <div id="app-body" className="flex h-screen w-screen">
        <div id="outer-nav" className="w-20">
          <SideNav
            serverModalToggle={serverModalToggle}
            serverButtonRef={serverButtonRef}
            botModalToggle={botModalToggle}
            botButtonRef={botButtonRef}
            currentTab={currentTab}
            currentTabSetter={currentTabSetter}
          />
        </div>
        <div id="inner-nav" className="w-52">
          <InnerNav
            currentTab={currentTab}
            directMessageButtonRef={directMessageButtonRef}
            dmModalToggle={dmModalToggle}
            selectedInnerTab={selectedInnerTab}
            setSelectedInnerTab={setSelectedInnerTab}
          />
        </div>
        <div id="center-page" ref={scrollableRef} className="flex-1">
          {currentTab == "DMS" ? (
            <div className="">
              <DMPages selectedInnerTab={selectedInnerTab} />
            </div>
          ) : null}
          {currentTab === "PublicServers" &&
          (selectedInnerTab === "Finance & Economics" ||
            selectedInnerTab === "Music" ||
            selectedInnerTab === "Entertainment" ||
            selectedInnerTab === "Gaming" ||
            selectedInnerTab === "Education" ||
            selectedInnerTab === "Science & Technology" ||
            selectedInnerTab === "Made By Weave") ? (
            <div className="">
              <PublicServersPages selectedInnerTab={selectedInnerTab} />
            </div>
          ) : null}
        </div>
      </div>
      <div>
        {serverModalShowing ? (
          <ServerModal serverModalRef={serverModalRef} />
        ) : null}
        {botModalShowing ? <BotServiceModal botModalRef={botModalRef} /> : null}
        {direcMessageModalShowing ? (
          <DirectMessageModal directMessageModalRef={directMessageModalRef} />
        ) : null}
      </div>
    </div>
  );
};

export default index;
